export const ActionNames = {
  // Alerts
  SET_ALERT: "SET_ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",

  // Mixer
  FETCH_ACCESS_TOKEN: "FETCH_ACCESS_TOKEN",
  FETCH_ACCESS_TOKEN_SUCCESS: "FETCH_ACCESS_SUCCESS",
  FETCH_ACCESS_TOKEN_FAILURE: "FETCH_ACCESS_TOKEN_FAILURE",

  // User Profile
  FETCH_USER_PROFILE: "FETCH_USER_PROFILE",
  FETCH_USER_PROFILE_SUCCESS: "FETCH_USER_PROFILE_SUCCESS",
  FETCH_USER_PROFILE_FAILURE: "FETCH_USER_PROFILE_FAILURE",

  // User Playlists
  FETCH_USER_PLAYLISTS: "FETCH_USER_PLAYLISTS",
  FETCH_USER_PLAYLISTS_SUCCESS: "FETCH_USER_PLAYLISTS_SUCCESS",
  FETCH_USER_PLAYLISTS_FAILURE: "FETCH_USER_PLAYLISTS_FAILURE",
  COMBINE_PLAYLISTS: "COMBINE_PLAYLISTS",
};
