export const ActionNames = {
  // Alerts
  SET_ALERT: "SET_ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",

  // User Profile
  FETCH_USER_PROFILE: "FETCH_USER_PROFILE",
  FETCH_USER_PROFILE_SUCCESS: "FETCH_USER_PROFILE_SUCCESS",
  FETCH_USER_PROFILE_FAILURE: "FETCH_USER_PROFILE_FAILURE",

  // User Playlists
  FETCH_USER_PLAYLISTS: "FETCH_USER_PLAYLISTS",
  FETCH_USER_PLAYLISTS_SUCCESS: "FETCH_USER_PLAYLISTS_SUCCESS",
  FETCH_USER_PLAYLISTS_FAILURE: "FETCH_USER_PLAYLISTS_FAILURE",
  COMBINE_PLAYLISTS: "COMBINE_PLAYLISTS",
};
