const ActionNames = {
  FETCH_USER_PROFILE: "FETCH_USER_PROFILE",
  FETCH_USER_PROFILE_SUCCESS: "FETCH_USER_PROFILE_SUCCESS",
  FETCH_USER_PROFILE_FAILTURE: "FETCH_USER_PROFILE_FAILTURE",

  FETCH_USER_PLAYLISTS: "FETCH_USER_PLAYLISTS",
  FETCH_USER_PLAYLISTS_SUCCESS: "FETCH_USER_PLAYLISTS_SUCCESS",
  FETCH_USER_PLAYLISTS_FAILURE: "FETCH_USER_PLAYLISTS_FAILURE",

  SET_TOKEN: "SET_TOKEN",

  SET_ALERT: "SET_ALERT",
  CLEAR_ALERTS: "CLEAR_ALERTS",
};

export default ActionNames;
