version: "3"

services:
  api:
    container_name: mymixtape-api
    build: ./mymixtape-api
    ports:
      - 8080:8080
  app:
    container_name: mymixtape-app
    build:
      context: ./mymixtape-app
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./mymixtape-app:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
